manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob/zmk/tree/mouse-3.2
  projects:
    - name: zmk
      remote: urob
      revision: mouse-keys
      import: app/west.yml
  self:
    path: config
